"""add senha to users

Revision ID: 5115a71cca9b
Revises: c0b5220e423d
Create Date: 2026-01-09 00:48:52.110349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5115a71cca9b'
down_revision: Union[str, Sequence[str], None] = 'c0b5220e423d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###
