"""init schema

Revision ID: 8b5e4134f3d2
Revises: 
Create Date: 2026-01-08 02:09:16.605045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5e4134f3d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UNIDADE_SAUDE',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Cnes', sa.Integer(), nullable=True),
    sa.Column('tipo_unidade', sa.String(), nullable=True),
    sa.Column('veiculos_sus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('perfil', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Gestao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_gse', sa.String(), nullable=True),
    sa.Column('esfer_adm', sa.Boolean(), nullable=True),
    sa.Column('retencao', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['UNIDADE_SAUDE.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Lacalization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_uf_municipio', sa.Integer(), nullable=True),
    sa.Column('regiao_saude', sa.String(), nullable=True),
    sa.Column('microregiao', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['UNIDADE_SAUDE.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Leitos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leitos_tipo_1', sa.Integer(), nullable=True),
    sa.Column('leitos_tipo_2', sa.Integer(), nullable=True),
    sa.Column('leito_tipo_3', sa.Integer(), nullable=True),
    sa.Column('total_leitos', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['UNIDADE_SAUDE.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Leitos')
    op.drop_table('Lacalization')
    op.drop_table('Gestao')
    op.drop_table('users')
    op.drop_table('UNIDADE_SAUDE')
    # ### end Alembic commands ###
