"""estrutura inicial

Revision ID: fe42cecc681a
Revises: 
Create Date: 2026-01-21 21:10:59.786408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe42cecc681a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidade_saude',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cnes', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidade_saude_cnes'), 'unidade_saude', ['cnes'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('perfil', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gestao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo_gestao', sa.String(length=10), nullable=True),
    sa.Column('esfera_admin', sa.String(length=10), nullable=True),
    sa.Column('retencao', sa.String(length=10), nullable=True),
    sa.Column('unidade_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade_saude.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leitos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('leitos_tipo_1', sa.Integer(), nullable=True),
    sa.Column('leitos_tipo_2', sa.Integer(), nullable=True),
    sa.Column('leitos_tipo_3', sa.Integer(), nullable=True),
    sa.Column('total_leitos', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade_saude.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cod_uf_municipio', sa.Integer(), nullable=False),
    sa.Column('regiao_saude', sa.String(length=100), nullable=True),
    sa.Column('microregiao', sa.String(length=100), nullable=True),
    sa.Column('unidade_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade_saude.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('leitos')
    op.drop_table('gestao')
    op.drop_table('users')
    op.drop_index(op.f('ix_unidade_saude_cnes'), table_name='unidade_saude')
    op.drop_table('unidade_saude')
    # ### end Alembic commands ###
